name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, mobile-optimization ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          # For main branch, deploy everything as is
          echo "Deploying main branch to root"
          
      - name: Build for beta branch
        if: github.ref == 'refs/heads/mobile-optimization'
        run: |
          # For mobile-optimization branch, create beta structure
          mkdir -p beta
          cp index.html beta/
          cp -r css beta/
          cp -r js beta/
          cp rules.html beta/
          cp README.md beta/
          cp beta-info.html beta/
          rm -rf beta/test
          rm -rf beta/*.bat
          rm -rf beta/*.ps1
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.ref == 'refs/heads/main' && '.' || './beta' }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
